server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jonathanvictoricadh/202305-Grupo4-Config
          default-label: main
          force-pull: true




